name: Daily Football Schedule

on:
  schedule:
    # Запуск каждый день в 06:00 UTC (это 09:00 МСК)
    - cron: '0 6 * * *'
  workflow_dispatch: # Позволяет запустить вручную для теста

jobs:
  send-schedule:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install python-telegram-bot requests python-dotenv

      - name: Run bot script
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          CHAT_ID: ${{ secrets.CHAT_ID }}
          FOOTBALL_API_KEY: ${{ secrets.FOOTBALL_API_KEY }}
        run: python bot.py